version: '3.8'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 7879maibui
      MYSQL_DATABASE: UserManager
      MYSQL_USER: admin
      MYSQL_PASSWORD: maibui7879
    ports:
      - "10000:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
